project:
  type: website

website:
  title: "Data Science Lab"
  navbar:
    left:
    - index.qmd
    - Alua.qmd
    - Ella.qmd
    - Jerry.qmd
    - Luuuu.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true